---
- name: web application deploy
  hosts: west
  remote_user: hank
  vars:
    workdir: /home/hank/code/src/github.com/ballPointPenguin/impulse-sieve
  tasks:
    - name: ensure code/src/github.com/ballPointPenguin directory is present
      file:
        path: /home/hank/code/src/github.com/ballPointPenguin
        state: directory

    - name: clone or update impulse-sieve repository
      git:
        accept_hostkey: yes
        dest: "{{ workdir }}"
        key_file: /home/hank/.ssh/id_rsa
        repo: "git@github.com:ballPointPenguin/impulse-sieve.git"
        update: yes

    - name: build docker image
      docker_image:
        force_source: yes
        name: impulse-sieve
        source: build
        build:
          path: "{{ workdir }}"
          pull: no

    - name: run docker container
      docker_container:
        expose: 80
        image: impulse-sieve
        name: impulse-sieve
        state: started
        env:
          LETSENCRYPT_HOST: "impulsesieve.art,www.impulsesieve.art"
          PORT: "80"
          VIRTUAL_HOST: "impulsesieve.art,www.impulsesieve.art"
